### ISSUE TITLE
Height above target button changes?? (Not high priority but control issue)

### ISSUE THREAD

**Issue by JulietMD** [F4b1n0u/quotation#3]
This is strange, but after I refresh the app on Expo app, the third time, the height above the orange target button gets smaller. I don't know why...not priority because at the end of the day the button works, but still a weird one that seems to not be in our control. Refer to images attached. 

![58419471_2203238433124921_5920623124889468928_n](https://user-images.githubusercontent.com/47000588/56755902-7228cb00-6788-11e9-84d1-5702e91c837e.jpg)

![58994456_427235894511246_8065950029291978752_n](https://user-images.githubusercontent.com/47000588/56755875-650bdc00-6788-11e9-8497-44dee0cbedc2.jpg)

**Comment by F4b1n0u** [comment]
it seems to be due to the status bar who disappears when we come back from a link
not sure why, sounds like a expo bug to me
