### ISSUE TITLE
If notifications are dismissed...

### ISSUE THREAD

**Issue by JulietMD** [F4b1n0u/quotation#8]
When I loaded the app on Expo on my phone, the pop-up asking me if I would like to allow notifications came up, and I clicked 'Don't allow'. This dismiss warning came up (see image). Not sure if this is something to be addressed or not... but I thought I would flag it just in case. You can let me know whether this is something or nothing. 

![59823046_437348640167897_5433960719882125312_n](https://user-images.githubusercontent.com/47000588/57384521-b369a380-71a8-11e9-862d-8d116ff65101.jpg)

**Comment by F4b1n0u** [comment]
that is no bug, it's just due to the fact the app is not in product mode yet
